### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by andrewgdavis** [takari/takari-local-repository#6]
Any ideas what would cause this issue?

```
[ERROR] java.lang.Error: java.io.IOException: No such file or directory
java.util.concurrent.ExecutionException: java.lang.Error: java.io.IOException: No such file or directory
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at io.takari.maven.builder.smart.ProjectExecutorService.take(ProjectExecutorService.java:101)
    at io.takari.maven.builder.smart.SmartBuilderImpl.build(SmartBuilderImpl.java:162)
    at io.takari.maven.builder.smart.SmartBuilder.build(SmartBuilder.java:31)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.Error: java.io.IOException: No such file or directory
    at sun.nio.ch.FileKey.create(FileKey.java:46)
    at sun.nio.ch.SharedFileLockTable.<init>(FileLockTable.java:120)
    at sun.nio.ch.FileLockTable.newSharedFileLockTable(FileLockTable.java:47)
    at sun.nio.ch.FileChannelImpl.fileLockTable(FileChannelImpl.java:1039)
    at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1106)
    at org.eclipse.aether.connector.basic.PartialFile$LockFile.tryLock(PartialFile.java:126)
    at org.eclipse.aether.connector.basic.PartialFile$LockFile.lock(PartialFile.java:71)
    at org.eclipse.aether.connector.basic.PartialFile$LockFile.<init>(PartialFile.java:58)
    at org.eclipse.aether.connector.basic.PartialFile$Factory.newInstance(PartialFile.java:210)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:432)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No such file or directory
    at sun.nio.ch.FileKey.init(Native Method)
    at sun.nio.ch.FileKey.create(FileKey.java:44)
    ... 14 more
```

What steps would need to be taken to investigate further?

I think its a race condition between the underlying filesystem and the VM that is being used.  The failure is intermittent, but can be reproduced on a fairly regular basis:

mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T11:57:37+00:00)
Maven home: /usr/share/maven
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_65/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.4.14-boot2docker", arch: "amd64", family: "unix"

```
ls /usr/share/maven/lib/ext/
README.txt            takari-local-repository-0.11.2.jar
takari-filemanager-0.8.3.jar  takari-smart-builder-0.4.1.jar
```

**Comment by andrewgdavis** [comment]
Sorry for the confusion; this looks to be code related to the smart-builder.   I followed the link from
http://takari.io/book/30-team-maven.html#takari-smart-builder

which brought me here by default.

**Comment by ifedorenko** [comment]
I believe this is a bug in aether. We have massively multithreaded build and have to use `-Daether.connector.resumeDownloads=false`. 

Also note that we do not use takari-local-repository because of #5.

**Comment by andrewgdavis** [comment]
@ifedorenko thanks for the info.   

If you are not using the takari-local-repository, are you still able to run multiple mvn builds concurrently?   Or does the use of ```-Daether.connector.resumeDownloads=false```  only help for a singular multithreaded build?

**Comment by ifedorenko** [comment]
We do not share local repository among multiple concurrent builds.

`-Daether.connector.resumeDownloads=false` is supposed to resume failed downloads, due to network failures or build jvm crashes, for example. It is not related to multiple concurrent builds sharing the same local repository.

**Comment by cstamas** [comment]
This project is being archived, while main features are today provided by Maven Resolver 1.7+, see here https://maven.apache.org/resolver/local-repository.html#shared-access-to-local-repository
